apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-alerts-to-statuspage
  namespace: default
  labels:
    app: prometheus-alerts-to-statuspage
spec:
  selector:
    matchLabels:
      app: prometheus-alerts-to-statuspage
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-alerts-to-statuspage
    spec:
      containers:
        - name: prometheus-alerts-to-statuspage
          image: nathandeamer/prometheus-alerts-to-statuspage:latest
          imagePullPolicy: Never
          ports:
            - name: http-web
              containerPort: 8080
          env:
            - name: STATUSPAGE_APIKEY
              valueFrom:
                secretKeyRef:
                  name: statuspage
                  key: apikey