apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-alerts-to-statuspage.fullname" . }}
type: Opaque
data:
  apikey: {{ .Values.statuspage.apikey | default "REPLACE ME" | b64enc | quote }}