apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alerts
spec:
  groups:
    - name: team1-alerts
      rules:
        - alert: Checkout-Customer-High-Error-Rate
          expr: vector(0) > 0
          labels:
            owner: team1
            namespace: default
            statuspage: true # Used for matchers - so needs to be a label
            statuspagePageId: lgbxhqm818kw # Used for grouping - so needs to be a label
            statuspageComponentId: 818336q5bjxv # Used for grouping - so needs to be a label
          annotations:
            statuspageComponentName: Checkout (Customer)
            statuspageStatus: identified # identified|investigating|monitoring|resolved
            statuspageImpactOverride: none  # none|maintenance|minor|major|critical
            statuspageComponentStatus: degraded_performance # none|operational|under_maintenance|degraded_performance|partial_outage|major_outage
            statuspageSummary: Customer checkout has a high error rate coming from our APIs

    - name: team2-alerts
      rules:
        - alert: Checkout-Customer-No-Orders-Created
          expr: vector(0) > 0
          labels:
            owner: team2
            namespace: default
            statuspage: true # Used for matchers - so needs to be a label
            statuspagePageId: lgbxhqm818kw # Used for grouping - so needs to be a label
            statuspageComponentId: 818336q5bjxv # Used for grouping - so needs to be a label
          annotations:
            statuspageComponentName: Checkout (Customer)
            statuspageStatus: identified # identified|investigating|monitoring|resolved
            statuspageImpactOverride: major  # none|maintenance|minor|major|critical
            statuspageComponentStatus: partial_outage # none|operational|under_maintenance|degraded_performance|partial_outage|major_outage
            statuspageSummary: Customer checkout has seen no orders being created in the last 10 minutes.

    - name: team3-alerts
      rules:
        - alert: Checkout-Customer-Synthetic-Test-Failure
          expr: vector(0) > 0
          labels:
            owner: team3
            namespace: default
            statuspageO: true # Used for matchers - so needs to be a label
            statuspagePageId: lgbxhqm818kw # Used for grouping - so needs to be a label
            statuspageComponentId: 818336q5bjxv # Used for grouping - so needs to be a label
          annotations:
            statuspageComponentName: Checkout (Customer)
            statuspageStatus: identified # identified|investigating|monitoring|resolved
            statuspageImpactOverride: critical  # none|maintenance|minor|major|critical
            statuspageComponentStatus: major_outage # none|operational|under_maintenance|degraded_performance|partial_outage|major_outage
            statuspageSummary: Customer checkout synthetic tests are failing
