apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alerts
spec:
  groups:
    - name: team1-alerts
      rules:
        - alert: Checkout-Customer-High-Error-Rate
          expr: vector(0) > 0
          labels:
            owner: team1
            namespace: default
            statusPageIO: true # Used for matchers - so needs to be a label
            statusPageIOPageId: abc # Used for grouping - so needs to be a label
            statusPageIOComponentId: 123 # Used for grouping - so needs to be a label
          annotations:
            statusPageIOComponentName: Checkout (Customer)
            statusPageIOStatus: identified # identified|investigating|monitoring|resolved
            statusPageIOImpactOverride: none  # none|maintenance|minor|major|critical
            statusPageIOComponentStatus: degraded_performance # none|operational|under_maintenance|degraded_performance|partial_outage|major_outage
            statusPageIOSummary: Customer checkout has a high error rate coming from our APIs

    - name: team2-alerts
      rules:
        - alert: Checkout-Customer-No-Orders-Created
          expr: vector(0) > 0
          labels:
            owner: team2
            namespace: default
            statusPageIO: true # Used for matchers - so needs to be a label
            statusPageIOPageId: abc # Used for grouping - so needs to be a label
            statusPageIOComponentId: 123 # Used for grouping - so needs to be a label
          annotations:
            statusPageIOComponentName: Checkout (Customer)
            statusPageIOStatus: identified # identified|investigating|monitoring|resolved
            statusPageIOImpactOverride: major  # none|maintenance|minor|major|critical
            statusPageIOComponentStatus: partial_outage # none|operational|under_maintenance|degraded_performance|partial_outage|major_outage
            statusPageIOSummary: Customer checkout has seen no orders being created in the last 10 minutes.  

    - name: team3-alerts
      rules:
        - alert: Checkout-Customer-Synthetic-Test-Failure
          expr: vector(0) > 0
          labels:
            owner: team3
            namespace: default
            statusPageIO: true # Used for matchers - so needs to be a label
            statusPageIOPageId: abc # Used for grouping - so needs to be a label
            statusPageIOComponentId: 123 # Used for grouping - so needs to be a label
          annotations:
            statusPageIOComponentName: Checkout (Customer)
            statusPageIOStatus: identified # identified|investigating|monitoring|resolved
            statusPageIOImpactOverride: critical  # none|maintenance|minor|major|critical
            statusPageIOComponentStatus: major_outage # none|operational|under_maintenance|degraded_performance|partial_outage|major_outage
            statusPageIOSummary: Customer checkout synthetic tests are failing
