name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'liberica'

    - name: Build Docker image
      run: ./gradlew bootBuildImage --imageName=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/prometheus-alerts-to-statuspage
    
    - name: Tag docker image
      run: |
        docker tag ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/prometheus-alerts-to-statuspage ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/prometheus-alerts-to-statuspage:${{ github.sha }}
        docker tag ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/prometheus-alerts-to-statuspage ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/prometheus-alerts-to-statuspage:latest

    - name: Login to Docker
      uses: docker/login-action@v2
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Push all tags
      run: docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/prometheus-alerts-to-statuspage --all-tags

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      id: install

    - name: Set Chart versions
      uses: mikefarah/yq@master
      with:
        cmd: yq -i '.version = "0.1.${{ github.run_number }}" | .appVersion = "${{ github.sha }}"' helm/Chart.yaml

    - name: Helm lint
      run: helm lint helm/ --set statuspage.apikey="YOUR_API_KEY_HERE"

    - name: Helm package
      run: helm package helm/

    - name: Helm push
      run: helm push prometheus-alerts-to-statuspage-0.1.${{ github.run_number }}.tgz oci://registry-1.docker.io/nathandeamer